# Generated by Django 5.1.4 on 2025-01-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="update_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
