# Generated by Django 5.1.5 on 2025-01-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_category_post_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
    ]
