# left ----------------------------
class SavingAccount: ...
class CheckingAccount: ...
class BankAccount(SavingAccount, CheckingAccount): ...


# right ---------------------------
class Stock: ...
class Bond: ...
class Security(Stock, Bond): ...


# center---------------------------
class InteresetBearingItem(BankAccount, Security): ...
class RealEstate: ...
class Asset(BankAccount, Security, RealEstate): ...
class Insurabletem(RealEstate, BankAccount): ...
