# Generated by Django 5.1.4 on 2025-01-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_create_at_post_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
