# Generated by Django 5.1.4 on 2025-01-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rate",
            field=models.IntegerField(null=True),
        ),
    ]
