# Generated by Django 5.1.4 on 2025-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
